import type { RtBlastRadius, RtTaskKind } from "./types";

export const TICK_MS = 500;
export const GAME_MINUTES_PER_REAL_SECOND = 1;
export const GAME_MINUTES_PER_TICK = 0.5;
export const GAME_DAY_START_MINUTE = 8 * 60;
export const RELEASE_TRAIN_GAME_MINUTE = 18 * 60;
export const GAME_DAY_MINUTES = RELEASE_TRAIN_GAME_MINUTE - GAME_DAY_START_MINUTE;
export const DAYS_PER_WEEK = 5;
export const WEEKS_PER_MONTH = 2;
export const MONTHS_PER_QUARTER = 2;
export const QUARTERS_PER_YEAR = 4;
export const DAYS_PER_MONTH = DAYS_PER_WEEK * WEEKS_PER_MONTH;
export const DAYS_PER_QUARTER = DAYS_PER_MONTH * MONTHS_PER_QUARTER;
export const DAYS_PER_YEAR = DAYS_PER_QUARTER * QUARTERS_PER_YEAR;
export const LEGACY_REVIEW_DAYS = DAYS_PER_WEEK;
export const DONE_REWORK_TRUST_COST = 4;

export const HORIZON_GOAL_CONFIG = {
  week: {
    expectedValue: 75,
    trust: 45,
    rewardBudget: 0,
    rewardProcessBoost: 0,
    missedTrustPenalty: 4,
  },
  month: {
    expectedValue: 150,
    trust: 48,
    rewardBudget: 1,
    rewardProcessBoost: 1,
    missedTrustPenalty: 6,
  },
  quarter: {
    expectedValue: 320,
    trust: 52,
    rewardBudget: 3,
    rewardProcessBoost: 5,
    missedTrustPenalty: 8,
  },
  year: {
    expectedValue: 1200,
    trust: 55,
    rewardBudget: 4,
    rewardProcessBoost: 0,
    missedTrustPenalty: 10,
  },
} as const;
export const MAX_HORIZON_TRUST_DAMAGE_PER_DAY = 10;

export const OUTSOURCE_COST_BY_IMPORTANCE = {
  optional: 3,
  important: 4,
  critical: 6,
} as const;
export const OUTSOURCE_QA_TEST_SKILL = 3;
export const OUTSOURCE_QA_ROLE_FIT = 3;

export const NIGHT_STAMINA_MIN_RECOVERY = 55;
export const NIGHT_STAMINA_RECOVERY_RATIO = 0.8;

export const FIRST_SPAWN_MIN_MS = 80000;
export const FIRST_SPAWN_MAX_MS = 120000;
export const SPAWN_INTERVAL_MIN_MS = 90000;
export const SPAWN_INTERVAL_MAX_MS = 150000;
export const LOW_WORK_SPAWN_MIN_MS = 25000;
export const LOW_WORK_SPAWN_MAX_MS = 45000;
export const BURST_INTERVAL_MIN_MS = 420000;
export const BURST_INTERVAL_MAX_MS = 660000;

export const WORK_SPEED_MULTIPLIER = 0.38;
export const ANALYSIS_SPEED_MULTIPLIER = 0.24;
export const WORK_STAMINA_DRAIN_BASE = 0.28;
export const WORK_PRESSURE_STAMINA_DRAIN = 0.045;
export const WORK_COMPLEXITY_STAMINA_DRAIN = 0.02;
export const OFF_ROLE_STAMINA_DRAIN = 0.12;
export const ANALYSIS_STAMINA_DRAIN_BASE = 0.23;
export const ANALYSIS_PRESSURE_STAMINA_DRAIN = 0.025;
export const ANALYSIS_COMPLEXITY_STAMINA_DRAIN = 0.012;
export const WORK_ASSIGNMENT_CANCEL_PROGRESS_PENALTY = 8;
export const WORK_ASSIGNMENT_CANCEL_STAMINA_PENALTY = 12;
export const WORK_ASSIGNMENT_CANCEL_SHOCK_MINUTES = 20;
export const WORK_OFF_ROLE_SKILL_THRESHOLD = 3;
export const WORK_CLARITY_FACTOR_BASE = 0.55;
export const WORK_CLARITY_FACTOR_DIVISOR = 140;
export const WORK_STAMINA_FACTOR_BASE = 0.55;
export const WORK_STAMINA_FACTOR_DIVISOR = 160;
export const WORK_STAMINA_FACTOR_MIN = 0.55;
export const WORK_STAMINA_FACTOR_MAX = 1.15;
export const WORK_SHOCK_SPEED_FACTOR = 0.65;
export const WORK_OFF_ROLE_SPEED_FACTOR = 0.62;
export const WORK_BASE_SPEED = 4.2;
export const WORK_SKILL_SPEED_FACTOR = 1.25;
export const WORK_COMPLEXITY_SPEED_FACTOR = 0.28;
export const WORK_LOW_STAMINA_BURNOUT_THRESHOLD = 20;
export const WORK_BURNOUT_DRAIN_BASE = 0.06;
export const WORK_BURNOUT_PRESSURE_DRAIN = 0.012;
export const WORK_BURNOUT_OFF_ROLE_DRAIN = 0.025;
export const WORK_IMPORTANCE_WEIGHT_CRITICAL = 35;
export const WORK_IMPORTANCE_WEIGHT_IMPORTANT = 20;
export const WORK_IMPORTANCE_WEIGHT_OPTIONAL = 8;
export const WORK_ANALYSIS_CLARITY_GAIN_BASE = 18;
export const WORK_ANALYSIS_CLARITY_GAIN_PER_SKILL = 5;
export const WORK_ANALYSIS_CLARITY_GAIN_RANDOM_MAX = 8;
export const WORK_ANALYSIS_QUALITY_GAIN_RATIO = 0.15;
export const WORK_SUBTASK_XP_ON_ROLE = 1;
export const WORK_SUBTASK_XP_OFF_ROLE = 3;
export const WORK_SUBTASK_XP_TO_SPECIALTY = 10;
export const WORK_SUBTASK_SPECIALTY_MAX = 5;
export const WORK_SUBTASK_SPECIALTY_GAIN = 1;
export const WORK_OFF_ROLE_CRITICAL_PENALTY = 10;
export const WORK_OFF_ROLE_DEFAULT_PENALTY = 6;
export const WORK_OFF_ROLE_STAMINA_PENALTY = 12;
export const WORK_QA_SUBTASK_COVERAGE_BASE = 22;
export const WORK_QA_SUBTASK_SKILL_FACTOR = 6;
export const WORK_QA_SUBTASK_ROLE_FACTOR = 4;
export const WORK_QA_SUBTASK_RANDOM_MAX = 8;
export const WORK_QA_OFF_ROLE_COVERAGE_FACTOR = 0.72;
export const WORK_QA_TRIAGE_MIN = 1;
export const WORK_QA_TRIAGE_SKILL_DIVISOR = 4;
export const WORK_QA_TRIAGE_RANDOM_MAX = 1;
export const WORK_IMPLEMENTATION_QUALITY_CRITICAL = 14;
export const WORK_IMPLEMENTATION_QUALITY_IMPORTANT = 9;
export const WORK_IMPLEMENTATION_QUALITY_OPTIONAL = 5;
export const WORK_CHANGED_AFTER_QA_COVERAGE_CAP = 35;
export const WORK_RAW_QUALITY_CLARITY_FACTOR = 0.55;
export const WORK_RAW_QUALITY_ROLE_FACTOR = 9;
export const WORK_RAW_QUALITY_RANDOM_MIN = -10;
export const WORK_RAW_QUALITY_RANDOM_MAX = 10;
export const WORK_RAW_QUALITY_STAMINA_PENALTY = 0.12;
export const WORK_RAW_QUALITY_OFF_ROLE_PENALTY = 18;
export const WORK_BUGFIX_QUALITY_BASE = 16;
export const WORK_BUGFIX_QUALITY_ROLE_FACTOR = 3;
export const WORK_IMPLEMENTATION_MIN_QUALITY_GAIN = 4;
export const WORK_IMPLEMENTATION_QUALITY_GAIN_DIVISOR = 8;
export const WORK_BUGFIX_MULTI_FIX_ROLE_THRESHOLD = 4;
export const WORK_BUGFIX_MULTI_FIX_CHANCE = 0.35;
export const WORK_BUGFIX_MULTI_FIX_COUNT = 2;
export const WORK_BUGFIX_DEFAULT_FIX_COUNT = 1;
export const WORK_TEST_COVERAGE_BASE = 24;
export const WORK_TEST_COVERAGE_SKILL_FACTOR = 8;
export const WORK_TEST_COVERAGE_RANDOM_MAX = 8;
export const WORK_ASSIGNMENT_ROLE_SCORE_FACTOR = 12;
export const WORK_ASSIGNMENT_ROLE_MATCH_BONUS = 10;
export const WORK_ASSIGNMENT_NON_PREFERRED_PENALTY = 28;
export const WORK_ASSIGNMENT_PROGRESS_PENALTY = 0.15;
export const WORK_PREFERRED_STRONG_SKILL_THRESHOLD = 4;
export const WORK_PREFERRED_STRONG_SKILL_DELTA = 1;
export const WORK_BUGFIX_PREFERRED_SKILL_THRESHOLD = 3;
export const WORK_ANALYSIS_REVEAL_HIGH_GAIN = 38;
export const WORK_ANALYSIS_REVEAL_MEDIUM_GAIN = 28;
export const WORK_ANALYSIS_REVEAL_HIGH_COUNT = 3;
export const WORK_ANALYSIS_REVEAL_MEDIUM_COUNT = 2;
export const WORK_ANALYSIS_REVEAL_LOW_COUNT = 1;

export const BACKLOG_LIMIT = 5;
export const BACKLOG_VALUE_DECAY_GAME_MINUTES = 900;
export const BACKLOG_VALUE_DECAY_MS = BACKLOG_VALUE_DECAY_GAME_MINUTES * 1000;
export const BACKLOG_EXPIRED_DEBT_VALUE_DIVISOR = 30;
export const BACKLOG_EXPIRED_DEBT_MIN = 1;
export const BACKLOG_EXPIRED_DEBT_MAX = 4;
export const MAX_BACKLOG_DECAY_DEBT_PER_DAY = 6;
export const FALLOUT_BACKLOG_EXTRA_SLOTS = 2;
export const MAX_FALLOUT_CHAIN_DEPTH = 2;
export const LATE_RELEASE_GRACE_MS = 30000;
export const LATE_RELEASE_FIRST_HALF_HOUR_PENALTY_PER_HOUR = 0.1;
export const LATE_RELEASE_AFTER_HALF_HOUR_PENALTY_PER_HOUR = 0.16;
export const LATE_RELEASE_PRESSURE_BASELINE = 3;
export const LATE_RELEASE_PRESSURE_PENALTY = 0.025;
export const LATE_RELEASE_KIND_SENSITIVITY: Record<RtTaskKind, number> = {
  feature: 1,
  bug: 0.9,
  techDebt: 0.45,
  integration: 1.2,
  incident: 1.25,
  performance: 0.9,
  compliance: 1.2,
};
export const LATE_RELEASE_BLAST_SENSITIVITY: Record<RtBlastRadius, number> = {
  low: 0,
  medium: 0.05,
  high: 0.12,
};
export const LATE_RELEASE_MAX_VALUE_PENALTY: Record<RtTaskKind, number> = {
  feature: 0.55,
  bug: 0.45,
  techDebt: 0.25,
  integration: 0.65,
  incident: 0.65,
  performance: 0.45,
  compliance: 0.65,
};
export const LATE_RELEASE_SCORE_PENALTY_WHEN_ON_TIME = 8;
export const LATE_RELEASE_SCORE_PENALTY_BASE = 6;
export const LATE_RELEASE_SCORE_PENALTY_PER_VALUE_PERCENT = 0.12;
export const LATE_RELEASE_SCORE_PENALTY_MIN = 8;
export const LATE_RELEASE_SCORE_PENALTY_MAX = 14;

export const RELEASE_QA_COVERAGE_THRESHOLD = 45;
export const RELEASE_LOW_CLARITY_THRESHOLD = 55;
export const RELEASE_DEADLINE_PRESSURE_RATIO = 0.18;
export const RELEASE_SCORE_DEADLINE_PRESSURE_RATIO = 0.2;
export const RELEASE_SCORE_DEADLINE_PRESSURE_PENALTY = 8;
export const RELEASE_SCORE_BUG_PENALTY = 12;
export const RELEASE_SCORE_DEBT_PENALTY_PER_DEBT = 0.12;
export const RELEASE_SCORE_QUALITY_WEIGHT = 0.45;
export const RELEASE_SCORE_CLARITY_WEIGHT = 0.25;
export const RELEASE_SCORE_QA_WEIGHT = 0.25;
export const RELEASE_SCORE_COMPLETED_RATIO_WEIGHT = 25;
export const RELEASE_SCORE_WORK_DONE_BONUS = 8;
export const RELEASE_SCORE_WORK_NOT_DONE_PENALTY = 18;
export const RELEASE_SCORE_OPEN_CRITICAL_PENALTY = 22;
export const RELEASE_SCORE_OPEN_IMPORTANT_PENALTY = 9;
export const RELEASE_SCORE_HIDDEN_OPEN_PENALTY = 10;

export const FRONTEND_GUARDRAIL_WINDOW = 7;
export const FRONTEND_GUARDRAIL_MIN_MAJOR_WORK = 1;
