import type { EngineLocale } from "./locale";
import type { RtTaskKind } from "./types";

export const TASK_TITLES: Record<EngineLocale, Record<RtTaskKind, string[]>> = {
  en: {
    feature: [
      "Add bonus payments",
      "Add CSV export",
      "Add user roles",
      "Add weekly report",
      "Add saved search",
      "Add notification preferences",
    ],
    bug: [
      "Fix login loop",
      "Fix duplicate charge",
      "Fix broken export",
      "Fix missing email",
      "Fix search timeout",
      "Fix permission error",
    ],
    techDebt: [
      "Refactor legacy payment module",
      "Clean old admin API",
      "Remove deprecated auth flow",
      "Improve test coverage",
      "Split report service",
      "Reduce frontend state hacks",
    ],
    integration: [
      "Connect billing provider",
      "Sync CRM contacts",
      "Import partner catalog",
      "Connect email gateway",
      "Add webhook receiver",
      "Sync analytics events",
    ],
    incident: [
      "Payment failures spike",
      "Login errors spike",
      "Emails stuck in queue",
      "Reports timeout in production",
      "Admin panel unavailable",
      "Search latency incident",
    ],
    performance: [
      "Optimize payment history query",
      "Reduce search latency",
      "Speed up report generation",
      "Cache admin dashboard",
      "Optimize notification worker",
      "Reduce auth DB load",
    ],
    compliance: [
      "Add audit log",
      "Export user data by request",
      "Mask sensitive fields",
      "Add permission review",
      "Add retention policy",
      "Add admin action history",
    ],
  },
  ru: {
    feature: [
      "Добавить бонусные платежи",
      "Добавить экспорт CSV",
      "Добавить роли пользователей",
      "Добавить еженедельный отчет",
      "Добавить сохраненный поиск",
      "Добавить настройки уведомлений",
    ],
    bug: [
      "Починить цикл логина",
      "Починить двойное списание",
      "Починить сломанный экспорт",
      "Починить пропавшее письмо",
      "Починить таймаут поиска",
      "Починить ошибку прав доступа",
    ],
    techDebt: [
      "Отрефакторить старый платежный модуль",
      "Очистить старый admin API",
      "Удалить устаревший auth flow",
      "Улучшить тестовое покрытие",
      "Разделить сервис отчетов",
      "Уменьшить хаки frontend-состояния",
    ],
    integration: [
      "Подключить биллинг-провайдера",
      "Синхронизировать CRM-контакты",
      "Импортировать каталог партнера",
      "Подключить email-шлюз",
      "Добавить webhook receiver",
      "Синхронизировать события аналитики",
    ],
    incident: [
      "Всплеск ошибок платежей",
      "Всплеск ошибок логина",
      "Письма застряли в очереди",
      "Отчеты таймаутятся в проде",
      "Админка недоступна",
      "Инцидент с задержкой поиска",
    ],
    performance: [
      "Оптимизировать запрос истории платежей",
      "Уменьшить задержку поиска",
      "Ускорить генерацию отчетов",
      "Закешировать админский дашборд",
      "Оптимизировать воркер уведомлений",
      "Уменьшить нагрузку auth DB",
    ],
    compliance: [
      "Добавить audit log",
      "Экспортировать данные пользователя по запросу",
      "Замаскировать чувствительные поля",
      "Добавить ревью прав доступа",
      "Добавить retention policy",
      "Добавить историю действий админа",
    ],
  },
};

export const SIM_TEXT: Record<
  EngineLocale,
  {
    subtasks: Record<string, string>;
  }
> = {
  en: {
    subtasks: {
      buildServerSideBehavior: "Build server-side behavior",
      buildUserFacingWorkflow: "Build user-facing workflow",
      supportUiWithServerBehavior: "Support UI with server-side behavior",
      wireUiState: "Wire UI state",
      validateHappyPath: "Validate happy path and edge cases",
      clarifyProductInteraction: "Clarify product interaction",
      prepareRolloutSafety: "Prepare rollout safety",
      fixRootCause: "Fix root cause",
      reproduceAndVerifyFix: "Reproduce and verify fix",
      addAlertForRecurrence: "Add alert for recurrence",
      refactorClientFlow: "Refactor brittle client-side flow",
      alignServerContract: "Align server contract",
      refactorRiskyModule: "Refactor risky module",
      runRegressionPass: "Run regression pass",
      cleanOperationalConfig: "Clean operational config",
      implementIntegrationContract: "Implement integration contract",
      handleTimeoutsAndRetries: "Handle timeouts and retries",
      validateFailureModes: "Validate failure modes",
      exposeIntegrationStatus: "Expose integration status",
      stabilizeProductionPath: "Stabilize production path",
      patchServiceBehavior: "Patch service behavior",
      smokeTestRecovery: "Smoke test recovery",
      reduceClientSideLatency: "Reduce client-side latency",
      watchProductionPressure: "Watch production pressure",
      reduceProductionPressure: "Reduce production pressure",
      optimizeHotPath: "Optimize hot path",
      loadTestCriticalScenario: "Load-test critical scenario",
      verifyComplianceScenario: "Verify compliance scenario",
      implementPolicyEnforcement: "Implement policy enforcement",
      addAuditRetentionSafety: "Add audit/retention safety",
      showCompliantUiCopy: "Show compliant UI copy",
      triageReportedBugs: "Triage reported bugs",
      retestAfterRework: "Re-test changes after rework",
      stabilizeProductionFailureMode: "Stabilize production failure mode",
      fixProductInteractionDefect: "Fix product interaction defect",
    },
  },
  ru: {
    subtasks: {
      buildServerSideBehavior: "Сделать серверное поведение",
      buildUserFacingWorkflow: "Сделать пользовательский сценарий",
      supportUiWithServerBehavior: "Поддержать UI серверным поведением",
      wireUiState: "Подключить состояние UI",
      validateHappyPath: "Проверить happy path и edge cases",
      clarifyProductInteraction: "Прояснить продуктовый сценарий",
      prepareRolloutSafety: "Подготовить безопасный rollout",
      fixRootCause: "Починить корневую причину",
      reproduceAndVerifyFix: "Воспроизвести и проверить fix",
      addAlertForRecurrence: "Добавить alert на повторение",
      refactorClientFlow: "Отрефакторить хрупкий клиентский сценарий",
      alignServerContract: "Согласовать серверный контракт",
      refactorRiskyModule: "Отрефакторить рискованный модуль",
      runRegressionPass: "Прогнать регрессию",
      cleanOperationalConfig: "Очистить operational config",
      implementIntegrationContract: "Реализовать контракт интеграции",
      handleTimeoutsAndRetries: "Обработать таймауты и retries",
      validateFailureModes: "Проверить failure modes",
      exposeIntegrationStatus: "Показать статус интеграции",
      stabilizeProductionPath: "Стабилизировать production path",
      patchServiceBehavior: "Починить поведение сервиса",
      smokeTestRecovery: "Smoke-test восстановления",
      reduceClientSideLatency: "Уменьшить задержку клиентского UI",
      watchProductionPressure: "Понаблюдать production pressure",
      reduceProductionPressure: "Снизить production pressure",
      optimizeHotPath: "Оптимизировать hot path",
      loadTestCriticalScenario: "Нагрузочно проверить критичный сценарий",
      verifyComplianceScenario: "Проверить комплаенс-сценарий",
      implementPolicyEnforcement: "Реализовать policy enforcement",
      addAuditRetentionSafety: "Добавить audit/retention safety",
      showCompliantUiCopy: "Показать compliant UI copy",
      triageReportedBugs: "Разобрать найденные баги",
      retestAfterRework: "Перепроверить изменения после доработки",
      stabilizeProductionFailureMode: "Стабилизировать production failure mode",
      fixProductInteractionDefect: "Починить дефект продуктового сценария",
    },
  },
};
