import type { EngineLocale } from "./locale";
import type { RtTaskKind } from "./types";

export const TASK_TITLES: Record<EngineLocale, Record<RtTaskKind, string[]>> = {
  en: {
    feature: [
      "Add bonus payments",
      "Add CSV export",
      "Add user roles",
      "Add weekly report",
      "Add saved search",
      "Add notification preferences",
    ],
    bug: [
      "Fix login loop",
      "Fix duplicate charge",
      "Fix broken export",
      "Fix missing email",
      "Fix search timeout",
      "Fix permission error",
    ],
    techDebt: [
      "Refactor legacy payment module",
      "Clean old admin API",
      "Remove deprecated login flow",
      "Improve test coverage",
      "Split report service",
      "Simplify frontend state",
    ],
    integration: [
      "Connect billing provider",
      "Sync CRM contacts",
      "Import partner catalog",
      "Connect email gateway",
      "Add webhook receiver",
      "Sync analytics events",
    ],
    incident: [
      "Payment failures spike",
      "Login errors spike",
      "Emails stuck in queue",
      "Reports time out in production",
      "Admin panel unavailable",
      "Search latency incident",
    ],
    performance: [
      "Optimize payment history query",
      "Reduce search latency",
      "Speed up report generation",
      "Cache admin dashboard",
      "Optimize notification worker",
      "Reduce auth DB load",
    ],
    compliance: [
      "Add audit log",
      "Export user data by request",
      "Mask sensitive fields",
      "Add permission review",
      "Add data retention rules",
      "Add admin action history",
    ],
  },
  ru: {
    feature: [
      "Добавить бонусные платежи",
      "Добавить экспорт CSV",
      "Добавить роли пользователей",
      "Добавить еженедельный отчет",
      "Добавить сохраненный поиск",
      "Добавить настройки уведомлений",
    ],
    bug: [
      "Починить цикл логина",
      "Починить двойное списание",
      "Починить сломанный экспорт",
      "Починить пропавшее письмо",
      "Починить таймаут поиска",
      "Починить ошибку прав доступа",
    ],
    techDebt: [
      "Разобрать старый платежный модуль",
      "Почистить старый API админки",
      "Убрать старый сценарий входа",
      "Улучшить тестовое покрытие",
      "Разделить сервис отчетов",
      "Упростить состояние фронтенда",
    ],
    integration: [
      "Подключить биллинг-провайдера",
      "Синхронизировать CRM-контакты",
      "Импортировать каталог партнера",
      "Подключить email-шлюз",
      "Добавить прием вебхуков",
      "Синхронизировать события аналитики",
    ],
    incident: [
      "Всплеск ошибок платежей",
      "Всплеск ошибок логина",
      "Письма застряли в очереди",
      "Отчеты зависают на проде",
      "Админка недоступна",
      "Инцидент с задержкой поиска",
    ],
    performance: [
      "Оптимизировать запрос истории платежей",
      "Уменьшить задержку поиска",
      "Ускорить генерацию отчетов",
      "Закешировать админский дашборд",
      "Оптимизировать воркер уведомлений",
      "Снизить нагрузку на базу входа",
    ],
    compliance: [
      "Добавить журнал аудита",
      "Экспортировать данные пользователя по запросу",
      "Замаскировать чувствительные поля",
      "Добавить проверку прав доступа",
      "Добавить правила хранения данных",
      "Добавить историю действий админа",
    ],
  },
};

export const SIM_TEXT: Record<
  EngineLocale,
  {
    subtasks: Record<string, string>;
  }
> = {
  en: {
    subtasks: {
      buildServerSideBehavior: "Implement server behavior",
      buildUserFacingWorkflow: "Build user path",
      supportUiWithServerBehavior: "Connect UI to server behavior",
      wireUiState: "Wire interface state",
      validateHappyPath: "Test main path and edge cases",
      clarifyProductInteraction: "Clarify user interaction",
      prepareRolloutSafety: "Prepare release safety",
      fixRootCause: "Fix root cause",
      reproduceAndVerifyFix: "Reproduce and verify the fix",
      addAlertForRecurrence: "Add recurrence warning",
      refactorClientFlow: "Simplify brittle client flow",
      alignServerContract: "Align server contract",
      refactorRiskyModule: "Refactor risky module",
      runRegressionPass: "Run regression pass",
      cleanOperationalConfig: "Clean operational config",
      implementIntegrationContract: "Implement integration contract",
      handleTimeoutsAndRetries: "Handle timeouts and retries",
      validateFailureModes: "Validate failure modes",
      exposeIntegrationStatus: "Expose integration status",
      stabilizeProductionPath: "Stabilize production path",
      patchServiceBehavior: "Patch service behavior",
      smokeTestRecovery: "Smoke-test recovery",
      reduceClientSideLatency: "Reduce client-side latency",
      watchProductionPressure: "Check production pressure",
      reduceProductionPressure: "Reduce production pressure",
      optimizeHotPath: "Optimize hot path",
      loadTestCriticalScenario: "Load-test critical scenario",
      verifyComplianceScenario: "Verify compliance requirements",
      implementPolicyEnforcement: "Implement policy enforcement",
      addAuditRetentionSafety: "Add audit/retention safety",
      showCompliantUiCopy: "Review compliant UI copy",
      triageReportedBugs: "Triage reported bugs",
      retestAfterRework: "Re-test changes after rework",
      stabilizeProductionFailureMode: "Stabilize production failure mode",
      fixProductInteractionDefect: "Fix product interaction defect",
    },
  },
  ru: {
    subtasks: {
      buildServerSideBehavior: "Реализовать серверную часть",
      buildUserFacingWorkflow: "Собрать пользовательский путь",
      supportUiWithServerBehavior: "Подключить серверную логику к интерфейсу",
      wireUiState: "Связать состояние интерфейса",
      validateHappyPath: "Проверить основной сценарий и крайние случаи",
      clarifyProductInteraction: "Уточнить поведение для пользователя",
      prepareRolloutSafety: "Подготовить безопасный выпуск",
      fixRootCause: "Починить корневую причину",
      reproduceAndVerifyFix: "Воспроизвести и проверить исправление",
      addAlertForRecurrence: "Добавить предупреждение о повторе",
      refactorClientFlow: "Упростить хрупкий клиентский код",
      alignServerContract: "Согласовать серверный контракт",
      refactorRiskyModule: "Разобрать рискованный модуль",
      runRegressionPass: "Прогнать регрессию",
      cleanOperationalConfig: "Почистить рабочую конфигурацию",
      implementIntegrationContract: "Реализовать контракт интеграции",
      handleTimeoutsAndRetries: "Обработать таймауты и повторы",
      validateFailureModes: "Проверить сценарии отказа",
      exposeIntegrationStatus: "Показать статус интеграции",
      stabilizeProductionPath: "Стабилизировать путь на проде",
      patchServiceBehavior: "Починить поведение сервиса",
      smokeTestRecovery: "Быстро проверить восстановление",
      reduceClientSideLatency: "Уменьшить задержку интерфейса",
      watchProductionPressure: "Проверить нагрузку на проде",
      reduceProductionPressure: "Снизить нагрузку на проде",
      optimizeHotPath: "Оптимизировать частый путь",
      loadTestCriticalScenario: "Нагрузочно проверить критичный сценарий",
      verifyComplianceScenario: "Проверить требования комплаенса",
      implementPolicyEnforcement: "Встроить проверку правил",
      addAuditRetentionSafety: "Добавить защиту аудита и хранения",
      showCompliantUiCopy: "Проверить текст на соответствие правилам",
      triageReportedBugs: "Разобрать найденные баги",
      retestAfterRework: "Перепроверить изменения после доработки",
      stabilizeProductionFailureMode: "Закрыть причину продовой поломки",
      fixProductInteractionDefect: "Починить сбой в пользовательском пути",
    },
  },
};
