import type {
  CharacterRole,
  CharacterTrait,
  Seniority,
  SkillMap,
  TaskDomain,
  TaskKind,
  TaskModifier,
  TaskRisk,
  WorkTrack,
} from "./types";

export const domainPrefixes: Record<TaskDomain, string> = {
  payments: "PAY",
  auth: "AUTH",
  admin: "ADM",
  search: "SRCH",
  reports: "REP",
  notifications: "NTF",
};

export const taskTitles: Record<TaskKind, string[]> = {
  feature: [
    "Add bonus payments",
    "Add CSV export",
    "Add user roles",
    "Add weekly report",
    "Add saved search",
    "Add notification preferences",
  ],
  bug: [
    "Fix login loop",
    "Fix duplicate charge",
    "Fix broken export",
    "Fix missing email",
    "Fix search timeout",
    "Fix permission error",
  ],
  techDebt: [
    "Refactor legacy payment module",
    "Clean old admin API",
    "Remove deprecated auth flow",
    "Improve test coverage",
    "Split report service",
    "Reduce frontend state hacks",
  ],
  integration: [
    "Connect billing provider",
    "Sync CRM contacts",
    "Import partner catalog",
    "Connect email gateway",
    "Add webhook receiver",
    "Sync analytics events",
  ],
  incident: [
    "Payment failures spike",
    "Login errors spike",
    "Emails stuck in queue",
    "Reports timeout in production",
    "Admin panel unavailable",
    "Search latency incident",
  ],
  performance: [
    "Optimize payment history query",
    "Reduce search latency",
    "Speed up report generation",
    "Cache admin dashboard",
    "Optimize notification worker",
    "Reduce auth DB load",
  ],
  compliance: [
    "Add audit log",
    "Export user data by request",
    "Mask sensitive fields",
    "Add permission review",
    "Add retention policy",
    "Add admin action history",
  ],
};

export const baseNeeds: Record<TaskKind, SkillMap> = {
  feature: {
    analysis: 40,
    design: 25,
    backend: 45,
    frontend: 35,
    review: 30,
    qa: 40,
    releaseSafety: 20,
  },
  bug: {
    analysis: 20,
    design: 5,
    backend: 35,
    frontend: 20,
    review: 25,
    qa: 50,
    releaseSafety: 10,
  },
  techDebt: {
    analysis: 10,
    design: 0,
    backend: 60,
    frontend: 10,
    review: 45,
    qa: 30,
    releaseSafety: 10,
  },
  integration: {
    analysis: 50,
    design: 10,
    backend: 60,
    frontend: 20,
    review: 40,
    qa: 55,
    releaseSafety: 35,
  },
  incident: {
    analysis: 15,
    design: 0,
    backend: 45,
    frontend: 10,
    review: 20,
    qa: 25,
    releaseSafety: 50,
  },
  performance: {
    analysis: 30,
    design: 0,
    backend: 70,
    frontend: 10,
    review: 40,
    qa: 40,
    releaseSafety: 45,
  },
  compliance: {
    analysis: 70,
    design: 20,
    backend: 35,
    frontend: 20,
    review: 45,
    qa: 70,
    releaseSafety: 30,
  },
};

export const taskKindBaseWeights: Record<TaskKind, number> = {
  feature: 35,
  bug: 15,
  techDebt: 10,
  integration: 15,
  incident: 5,
  performance: 10,
  compliance: 10,
};

export const sizeModifiers: Record<number, number> = {
  1: 0.7,
  2: 0.9,
  3: 1,
  4: 1.25,
  5: 1.5,
};

export const riskTemplates: Array<
  Omit<TaskRisk, "id" | "state"> & { tags?: TaskModifier[] }
> = [
  {
    type: "data_loss",
    severity: 3,
    discoverBy: ["analysis", "qa"],
    mitigateBy: ["analysis", "backend", "qa"],
    triggerText: "Partial refunds break accounting.",
    followupTaskKind: "bug",
  },
  {
    type: "regression",
    severity: 2,
    discoverBy: ["review", "qa"],
    mitigateBy: ["review", "qa"],
    triggerText: "Legacy module regression.",
    followupTaskKind: "bug",
    tags: ["legacy"],
  },
  {
    type: "wrong_scope",
    severity: 2,
    discoverBy: ["analysis"],
    mitigateBy: ["analysis", "design"],
    triggerText: "Unclear acceptance criteria.",
    followupTaskKind: "feature",
    tags: ["vague"],
  },
  {
    type: "wrong_scope",
    severity: 2,
    discoverBy: ["analysis"],
    mitigateBy: ["analysis"],
    triggerText: "VIP stakeholder changes scope.",
    followupTaskKind: "feature",
    tags: ["vip"],
  },
  {
    type: "ux_confusion",
    severity: 1,
    discoverBy: ["design", "qa"],
    mitigateBy: ["design", "frontend", "qa"],
    triggerText: "Missing empty state.",
    followupTaskKind: "bug",
    tags: ["customerVisible"],
  },
  {
    type: "performance",
    severity: 2,
    discoverBy: ["analysis", "review", "qa"],
    mitigateBy: ["backend", "review", "qa"],
    triggerText: "Slow query on large dataset.",
    followupTaskKind: "performance",
  },
  {
    type: "dependency",
    severity: 2,
    discoverBy: ["analysis"],
    mitigateBy: ["analysis", "releaseSafety"],
    triggerText: "Third-party API timeout.",
    followupTaskKind: "incident",
    tags: ["crossTeam"],
  },
  {
    type: "backend_bug",
    severity: 1,
    discoverBy: ["analysis", "qa"],
    mitigateBy: ["backend", "qa"],
    triggerText: "Timezone edge case.",
    followupTaskKind: "bug",
  },
  {
    type: "data_loss",
    severity: 3,
    discoverBy: ["analysis", "review", "qa"],
    mitigateBy: ["analysis", "backend", "review"],
    triggerText: "Permission leak.",
    followupTaskKind: "incident",
  },
  {
    type: "frontend_bug",
    severity: 1,
    discoverBy: ["review", "qa"],
    mitigateBy: ["frontend", "review", "qa"],
    triggerText: "Frontend state desync.",
    followupTaskKind: "bug",
  },
  {
    type: "release_blast_radius",
    severity: 2,
    discoverBy: ["releaseSafety", "review"],
    mitigateBy: ["releaseSafety"],
    triggerText: "No rollback plan.",
    followupTaskKind: "incident",
  },
  {
    type: "frontend_bug",
    severity: 1,
    discoverBy: ["qa"],
    mitigateBy: ["frontend", "qa"],
    triggerText: "QA misses mobile layout.",
    followupTaskKind: "bug",
  },
  {
    type: "backend_bug",
    severity: 2,
    discoverBy: ["analysis", "qa"],
    mitigateBy: ["backend", "qa"],
    triggerText: "Webhook retries duplicate events.",
    followupTaskKind: "bug",
  },
  {
    type: "data_loss",
    severity: 3,
    discoverBy: ["analysis", "qa"],
    mitigateBy: ["backend", "qa", "review"],
    triggerText: "Report export leaks hidden columns.",
    followupTaskKind: "incident",
  },
  {
    type: "performance",
    severity: 2,
    discoverBy: ["review", "qa"],
    mitigateBy: ["backend", "review", "releaseSafety"],
    triggerText: "Cache serves stale data.",
    followupTaskKind: "bug",
  },
  {
    type: "wrong_scope",
    severity: 2,
    discoverBy: ["analysis", "review"],
    mitigateBy: ["analysis", "review"],
    triggerText: "Admin action not audited.",
    followupTaskKind: "compliance",
  },
];

export const characterNames = [
  "Nina",
  "Oleg",
  "Mira",
  "Anton",
  "Lena",
  "Max",
  "Ira",
  "Roman",
  "Dasha",
  "Kirill",
  "Sasha",
  "Pavel",
  "Marina",
  "Denis",
  "Vera",
  "Tim",
  "Yana",
  "Egor",
  "Alina",
  "Victor",
];

export const baseSkillProfiles: Record<CharacterRole, SkillMap> = {
  analyst: {
    analysis: 4,
    design: 2,
    backend: 0,
    frontend: 0,
    review: 1,
    qa: 2,
    releaseSafety: 0,
  },
  designer: {
    analysis: 2,
    design: 4,
    backend: 0,
    frontend: 2,
    review: 1,
    qa: 1,
    releaseSafety: 0,
  },
  backend: {
    analysis: 1,
    design: 0,
    backend: 4,
    frontend: 1,
    review: 3,
    qa: 1,
    releaseSafety: 1,
  },
  frontend: {
    analysis: 1,
    design: 2,
    backend: 1,
    frontend: 4,
    review: 2,
    qa: 1,
    releaseSafety: 0,
  },
  qa: {
    analysis: 2,
    design: 1,
    backend: 1,
    frontend: 1,
    review: 2,
    qa: 4,
    releaseSafety: 1,
  },
  sre: {
    analysis: 1,
    design: 0,
    backend: 2,
    frontend: 0,
    review: 2,
    qa: 2,
    releaseSafety: 4,
  },
};

export const seniorityModifiers: Record<
  Seniority,
  { skillDelta: number; salary: number; growthRate: number; resilience: number }
> = {
  junior: {
    skillDelta: -1,
    salary: 1,
    growthRate: 1.5,
    resilience: 0.8,
  },
  middle: {
    skillDelta: 0,
    salary: 2,
    growthRate: 1,
    resilience: 1,
  },
  senior: {
    skillDelta: 1,
    salary: 4,
    growthRate: 0.7,
    resilience: 1.2,
  },
};

export const positiveTraits: CharacterTrait[] = [
  "fast",
  "careful",
  "mentor",
  "legacyExpert",
  "productSense",
];

export const negativeTraits: CharacterTrait[] = [
  "fragile",
  "sloppy",
  "soloist",
  "contextSwitchHater",
];

export const rolePreferredTracks: Record<CharacterRole, WorkTrack[]> = {
  analyst: ["analysis"],
  designer: ["design", "frontend"],
  backend: ["backend", "review"],
  frontend: ["frontend", "review"],
  qa: ["qa", "review"],
  sre: ["releaseSafety", "backend"],
};
